# PHD Launch Configuration
#

---
name: PHD Launcher
windows:
  - tabs:
      - title: PHD
        layout:
          split_direction: horizontal
          panes: 
            - cwd: "/Volumes/Seagate Bac/backups/My_Passport_20171225/backup_iomega/cdteb/bin/"
              commands:
                - exec: source venv/bin/activate
                - exec: ./phd.py add -d
            - cwd: "/Volumes/Seagate Bac/backups/My_Passport_20171225/backup_iomega/cdteb/bin/"
              commands:
                - exec: source venv/bin/activate
                - exec: open ../__pending
                - exec: ./phd.py run
